package com.packt.jdeveloper.cookbook.hr.departments.model.entity;


import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityDefImpl;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 22 15:30:06 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentImpl extends ExtEntityImpl {

    private static ExtEntityDefImpl mDefinitionObject;

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentImpl() {
    }

    /**
     * @param departmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number departmentId) {
        return new Key(new Object[]{departmentId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    (ExtEntityDefImpl)EntityDefImpl.findDefObject("com.packt.jdeveloper.cookbook.hr.departments.model.entity.Department");
        }
        return mDefinitionObject;
    }


    @Override
    protected void doDML(int i, TransactionEvent transactionEvent) {
        super.doDML(i, transactionEvent);
    }
}
