package com.packt.jdeveloper.cookbook.shared.bc.test.client;

import com.packt.jdeveloper.cookbook.shared.bc.test.common.HrAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 13 22:17:43 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrAppModuleClient extends ApplicationModuleImpl implements HrAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HrAppModuleClient() {
    }

    public void testSQLProcedure() {
        Object _ret =
            this.riInvokeExportedMethod(this,"testSQLProcedure",null,null);
        return;
    }
}
