package com.packt.jdeveloper.cookbook.hr.components.model.entity;

import com.packt.jdeveloper.cookbook.shared.bc.exceptions.ExtJboException;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityDefImpl;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 26 22:41:07 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentImpl extends ExtEntityImpl {

    @Override
    protected void doDML(int operation, TransactionEvent transactionEvent) {
        // check for insert
        if (DML_INSERT == operation) {
            // get the department employees accessor
            RowIterator departmentEmployees = this.getDepartmentEmployees();
            // check for any employees
            if (!departmentEmployees.hasNext()) {
                // avoid inserting the department if there are no employees for it
                throw new ExtJboException("00006");
            }
        }

        // allow DML to proceed
        super.doDML(operation, transactionEvent);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DepartmentId {
            public Object get(DepartmentImpl obj) {
                return obj.getDepartmentId();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setDepartmentId((Number)value);
            }
        },
        DepartmentName {
            public Object get(DepartmentImpl obj) {
                return obj.getDepartmentName();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setDepartmentName((String)value);
            }
        },
        ManagerId {
            public Object get(DepartmentImpl obj) {
                return obj.getManagerId();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setManagerId((Number)value);
            }
        },
        LocationId {
            public Object get(DepartmentImpl obj) {
                return obj.getLocationId();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setLocationId((Number)value);
            }
        },
        DepartmentEmployees {
            public Object get(DepartmentImpl obj) {
                return obj.getDepartmentEmployees();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        DepartmentManager {
            public Object get(DepartmentImpl obj) {
                return obj.getDepartmentManager();
            }

            public void put(DepartmentImpl obj, Object value) {
                obj.setDepartmentManager((ExtEntityImpl)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DepartmentImpl object);

        public abstract void put(DepartmentImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    private static ExtEntityDefImpl mDefinitionObject;
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME =
        AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int DEPARTMENTEMPLOYEES =
        AttributesEnum.DepartmentEmployees.index();
    public static final int DEPARTMENTMANAGER =
        AttributesEnum.DepartmentManager.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    (ExtEntityDefImpl)EntityDefImpl.findDefObject("com.packt.jdeveloper.cookbook.hr.components.model.entity.Department");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
     * @return the DepartmentId
     */
    public Number getDepartmentId() {
        return (Number)getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentId.
     * @param value value to set the DepartmentId
     */
    public void setDepartmentId(Number value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for DepartmentName, using the alias name DepartmentName.
     * @return the DepartmentName
     */
    public String getDepartmentName() {
        return (String)getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentName.
     * @param value value to set the DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for ManagerId, using the alias name ManagerId.
     * @return the ManagerId
     */
    public Number getManagerId() {
        return (Number)getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManagerId.
     * @param value value to set the ManagerId
     */
    public void setManagerId(Number value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the LocationId
     */
    public Number getLocationId() {
        return (Number)getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(Number value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartmentEmployees() {
        return (RowIterator)getAttributeInternal(DEPARTMENTEMPLOYEES);
    }


    /**
     * @return the associated entity com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityImpl.
     */
    public ExtEntityImpl getDepartmentManager() {
        return (ExtEntityImpl)getAttributeInternal(DEPARTMENTMANAGER);
    }

    /**
     * Sets <code>value</code> as the associated entity com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtEntityImpl.
     */
    public void setDepartmentManager(ExtEntityImpl value) {
        setAttributeInternal(DEPARTMENTMANAGER, value);
    }


    /**
     * @param departmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number departmentId) {
        return new Key(new Object[] { departmentId });
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        // get the department employeess accessor
        RowIterator departmentEmployees = this.getDepartmentEmployees();
        // iterate over all department employees
        while (departmentEmployees.hasNext()) {
            // get the department employee
            EmployeeImpl departmentEmployee =
                (EmployeeImpl)departmentEmployees.next();
            // remove employee
            departmentEmployee.remove();
        }
        super.remove();
    }
}
