package com.packt.jdeveloper.cookbook.shared.bc.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 13 22:17:43 EEST 2011
// ---------------------------------------------------------------------
public interface HrAppModule extends ApplicationModule {
    void testSQLProcedure();
}
