package com.packt.jdeveloper.cookbook.hr.components.model.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 05 19:17:25 EEST 2011
// ---------------------------------------------------------------------
public interface Employees extends ViewObject {
    void adjustCommission(Number commissionPctAdjustment);

}
