package com.packt.jdeveloper.cookbook.hr.components.model.view;


import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtApplicationModuleImpl;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtViewObjectImpl;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import oracle.jbo.domain.Number;
import oracle.jbo.server.QueryCollection;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 27 22:46:05 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeCountImpl extends ExtViewObjectImpl {

    private static final String DEFAULT_DEPARTMENT_ID_KEY = "DEFAULT_DEPARTMENT_ID";

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeCountImpl() {
    }

    /**
     * Returns the bind variable value for DepartmentId.
     * @return bind variable value for DepartmentId
     */
    public Number getDepartmentId() {
        return (Number)getNamedWhereClauseParam("DepartmentId");
    }

    /**
     * Sets <code>value</code> for bind variable DepartmentId.
     * @param value value to bind as DepartmentId
     */
    public void setDepartmentId(Number value) {
        setNamedWhereClauseParam("DepartmentId", value);
    }

    /**
     * Recipe: Overriding bindParametersForCollection() to set a View object bind variable.
     *
     * @param queryCollection
     * @param bindVariables
     * @param preparedStatement
     * @throws SQLException
     */
    @Override
    protected void bindParametersForCollection(QueryCollection queryCollection, Object[] bindVariables,
                                               PreparedStatement preparedStatement) throws SQLException {
        // if bind variable value has not been provided, provide a default setting
        if (this.getDepartmentId() == null) {
            // get default department id
            Number departmentId =
                ((Number)((ExtApplicationModuleImpl)this.getApplicationModule()).getCustomData(DEFAULT_DEPARTMENT_ID_KEY));
            // set bind variable right on the query to default variable
            if (departmentId != null) {
                super.setBindVariableValue(bindVariables, "DepartmentId", departmentId.toString());
                // set bind variable on View object as well, to be available for this time forward
                this.setDepartmentId(departmentId);
            }
        }

        // allow framework processing
        super.bindParametersForCollection(queryCollection, bindVariables, preparedStatement);
    }

}
